/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Answers without touching the database, so health checks never wake Aurora.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The API is running */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * First-run setup
         * @description Creates the workspace and its owner, then signs the owner in. Works once per deployment.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        workspaceName: string;
                        name: string;
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Workspace and owner created; the response sets the session cookie */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            workspaceId: string;
                            userId: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in member */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Who is signed in and their role */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            userId: string;
                            email: string;
                            role: string;
                            workspaceId: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Components and their groups, in page order */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Groups and components, each ordered by position */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            groups: {
                                /** Format: uuid */
                                id: string;
                                name: string;
                                position: number;
                            }[];
                            components: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                groupId: string | null;
                                name: string;
                                description: string | null;
                                position: number;
                                /** @enum {string} */
                                status: "operational" | "degraded_performance" | "partial_outage" | "major_outage" | "under_maintenance";
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Add a component at the end of the list */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        /** @default null */
                        description?: string | null;
                        /**
                         * Format: uuid
                         * @default null
                         */
                        groupId?: string | null;
                    };
                };
            };
            responses: {
                /** @description The new component */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            groupId: string | null;
                            name: string;
                            description: string | null;
                            position: number;
                            /** @enum {string} */
                            status: "operational" | "degraded_performance" | "partial_outage" | "major_outage" | "under_maintenance";
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/components/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a component from every page */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Done */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Rename, describe or regroup a component */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        description?: string | null;
                        /** Format: uuid */
                        groupId?: string | null;
                    };
                };
            };
            responses: {
                /** @description The updated component */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            groupId: string | null;
                            name: string;
                            description: string | null;
                            position: number;
                            /** @enum {string} */
                            status: "operational" | "degraded_performance" | "partial_outage" | "major_outage" | "under_maintenance";
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/components/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set the order of every component */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        ids: string[];
                    };
                };
            };
            responses: {
                /** @description Done */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/component-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a group at the end of the list */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description The new group */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            position: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/component-groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a group; its components stay, ungrouped */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Done */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Rename a group */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description The updated group */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            position: number;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/component-groups/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set the order of every group */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        ids: string[];
                    };
                };
            };
            responses: {
                /** @description Done */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/monitors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monitors, oldest first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Every monitor */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            monitors: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                componentId: string | null;
                                name: string;
                                /** @enum {string} */
                                type: "http";
                                http: {
                                    /** Format: uri */
                                    url: string;
                                    /**
                                     * @default GET
                                     * @enum {string}
                                     */
                                    method: "GET" | "HEAD";
                                    expectedStatus?: number[];
                                    keyword?: string;
                                    /** @default 10000 */
                                    timeoutMs: number;
                                    /** @default true */
                                    followRedirects: boolean;
                                };
                                /**
                                 * @default approve
                                 * @enum {string}
                                 */
                                publishPolicy: "auto" | "approve" | "internal_only";
                                /**
                                 * @default major_outage
                                 * @enum {string}
                                 */
                                downStatus: "partial_outage" | "major_outage";
                                /** @default {} */
                                detection: {
                                    /** @default 2 */
                                    failThreshold: number;
                                    /** @default 3 */
                                    recoverThreshold: number;
                                    /** @default 2 */
                                    quorum: number;
                                    /** @default null */
                                    degradedLatencyMs: number | null;
                                    /** @default 3 */
                                    staleAfterIntervals: number;
                                    /** @default 30 */
                                    flapWindowMinutes: number;
                                    /** @default 4 */
                                    flapMaxTransitions: number;
                                    /** @default 15 */
                                    stableMinutes: number;
                                };
                                /** @default true */
                                enabled: boolean;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Add a monitor; probes pick it up with the next config publish */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @default null
                         */
                        componentId?: string | null;
                        name: string;
                        /**
                         * @default http
                         * @enum {string}
                         */
                        type?: "http";
                        http: {
                            /** Format: uri */
                            url: string;
                            /**
                             * @default GET
                             * @enum {string}
                             */
                            method?: "GET" | "HEAD";
                            expectedStatus?: number[];
                            keyword?: string;
                            /** @default 10000 */
                            timeoutMs?: number;
                            /** @default true */
                            followRedirects?: boolean;
                        };
                        /**
                         * @default approve
                         * @enum {string}
                         */
                        publishPolicy?: "auto" | "approve" | "internal_only";
                        /**
                         * @default major_outage
                         * @enum {string}
                         */
                        downStatus?: "partial_outage" | "major_outage";
                        /** @default {} */
                        detection?: {
                            /** @default 2 */
                            failThreshold?: number;
                            /** @default 3 */
                            recoverThreshold?: number;
                            /** @default 2 */
                            quorum?: number;
                            /** @default null */
                            degradedLatencyMs?: number | null;
                            /** @default 3 */
                            staleAfterIntervals?: number;
                            /** @default 30 */
                            flapWindowMinutes?: number;
                            /** @default 4 */
                            flapMaxTransitions?: number;
                            /** @default 15 */
                            stableMinutes?: number;
                        };
                        /** @default true */
                        enabled?: boolean;
                    };
                };
            };
            responses: {
                /** @description The new monitor */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            componentId: string | null;
                            name: string;
                            /** @enum {string} */
                            type: "http";
                            http: {
                                /** Format: uri */
                                url: string;
                                /**
                                 * @default GET
                                 * @enum {string}
                                 */
                                method: "GET" | "HEAD";
                                expectedStatus?: number[];
                                keyword?: string;
                                /** @default 10000 */
                                timeoutMs: number;
                                /** @default true */
                                followRedirects: boolean;
                            };
                            /**
                             * @default approve
                             * @enum {string}
                             */
                            publishPolicy: "auto" | "approve" | "internal_only";
                            /**
                             * @default major_outage
                             * @enum {string}
                             */
                            downStatus: "partial_outage" | "major_outage";
                            /** @default {} */
                            detection: {
                                /** @default 2 */
                                failThreshold: number;
                                /** @default 3 */
                                recoverThreshold: number;
                                /** @default 2 */
                                quorum: number;
                                /** @default null */
                                degradedLatencyMs: number | null;
                                /** @default 3 */
                                staleAfterIntervals: number;
                                /** @default 30 */
                                flapWindowMinutes: number;
                                /** @default 4 */
                                flapMaxTransitions: number;
                                /** @default 15 */
                                stableMinutes: number;
                            };
                            /** @default true */
                            enabled: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/monitors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace a monitor's settings
         * @description Send every field; omitted optional fields fall back to their defaults.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @default null
                         */
                        componentId?: string | null;
                        name: string;
                        /**
                         * @default http
                         * @enum {string}
                         */
                        type?: "http";
                        http: {
                            /** Format: uri */
                            url: string;
                            /**
                             * @default GET
                             * @enum {string}
                             */
                            method?: "GET" | "HEAD";
                            expectedStatus?: number[];
                            keyword?: string;
                            /** @default 10000 */
                            timeoutMs?: number;
                            /** @default true */
                            followRedirects?: boolean;
                        };
                        /**
                         * @default approve
                         * @enum {string}
                         */
                        publishPolicy?: "auto" | "approve" | "internal_only";
                        /**
                         * @default major_outage
                         * @enum {string}
                         */
                        downStatus?: "partial_outage" | "major_outage";
                        /** @default {} */
                        detection?: {
                            /** @default 2 */
                            failThreshold?: number;
                            /** @default 3 */
                            recoverThreshold?: number;
                            /** @default 2 */
                            quorum?: number;
                            /** @default null */
                            degradedLatencyMs?: number | null;
                            /** @default 3 */
                            staleAfterIntervals?: number;
                            /** @default 30 */
                            flapWindowMinutes?: number;
                            /** @default 4 */
                            flapMaxTransitions?: number;
                            /** @default 15 */
                            stableMinutes?: number;
                        };
                        /** @default true */
                        enabled?: boolean;
                    };
                };
            };
            responses: {
                /** @description The updated monitor */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            componentId: string | null;
                            name: string;
                            /** @enum {string} */
                            type: "http";
                            http: {
                                /** Format: uri */
                                url: string;
                                /**
                                 * @default GET
                                 * @enum {string}
                                 */
                                method: "GET" | "HEAD";
                                expectedStatus?: number[];
                                keyword?: string;
                                /** @default 10000 */
                                timeoutMs: number;
                                /** @default true */
                                followRedirects: boolean;
                            };
                            /**
                             * @default approve
                             * @enum {string}
                             */
                            publishPolicy: "auto" | "approve" | "internal_only";
                            /**
                             * @default major_outage
                             * @enum {string}
                             */
                            downStatus: "partial_outage" | "major_outage";
                            /** @default {} */
                            detection: {
                                /** @default 2 */
                                failThreshold: number;
                                /** @default 3 */
                                recoverThreshold: number;
                                /** @default 2 */
                                quorum: number;
                                /** @default null */
                                degradedLatencyMs: number | null;
                                /** @default 3 */
                                staleAfterIntervals: number;
                                /** @default 30 */
                                flapWindowMinutes: number;
                                /** @default 4 */
                                flapMaxTransitions: number;
                                /** @default 15 */
                                stableMinutes: number;
                            };
                            /** @default true */
                            enabled: boolean;
                        };
                    };
                };
            };
        };
        post?: never;
        /** Delete a monitor; probes stop checking it with the next config publish */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Done */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
